name: readthedocs_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - libvips=8.12.2
  - python=3.11
  - pip=22.0.4
  - pip:
    - readthedocs-sphinx-search==0.1.0
    - myst-parser==0.15.1
    - sphinx-rtd-theme==0.5.2
    - sphinx-panels==0.6.0
    - sphinx-jsonschema==1.17.2
    - tissuumaps>=3.2rc3